### ISSUE TITLE
小程序支付提示需openid 文档里没间哪里设置openid

### ISSUE THREAD

**Issue by 377123** [lokielse/omnipay-wechatpay#111]
<!--
Omnipay\Common\Exception\InvalidRequestException: The open_id parameter is required in file /wwwroot/uniapp/vendor/omnipay/common/src/Common/ParametersTrait.php on line 80

#0 /wwwroot/uniapp/vendor/lokielse/omnipay-wechatpay/src/Message/CreateOrderRequest.php(42): Omnipay\Common\Message\AbstractRequest->validate('open_id')

**Comment by 377123** [comment]
<!--
Omnipay\Common\Exception\InvalidRequestException: The open_id parameter is required in file /wwwroot/uniapp/vendor/omnipay/common/src/Common/ParametersTrait.php on line 80

#0 /wwwroot/uniapp/vendor/lokielse/omnipay-wechatpay/src/Message/CreateOrderRequest.php(42): Omnipay\Common\Message\AbstractRequest->validate('open_id')

**Comment by 377123** [comment]
Omnipay\Common\Exception\InvalidRequestException: The open_id parameter is required in file /wwwroot/uniapp/vendor/omnipay/common/src/Common/ParametersTrait.php on line 80

#0 /wwwroot/uniapp/vendor/lokielse/omnipay-wechatpay/src/Message/CreateOrderRequest.php(42): Omnipay\Common\Message\AbstractRequest->validate('open_id')

**Comment by andytian123** [comment]
openid!=open_i
d

'openid'           => $this->getOpenId(),//*(trade_type=JSAPI)


public function getOpenId()
    {
        return $this->getParameter('open_id');
    }
