### ISSUE TITLE
申请加入到开发者团队里继续维护项目

### ISSUE THREAD

**Issue by dacheng-gao** [lokielse/omnipay-wechatpay#115]
Hi, @lokielse 

我从2016年开始使用这个扩展包并在后来贡献PR, 并且目前也经常有使用微信支付的场景, 希望能加入到协作者后续维护项目方便.

**Comment by hogus2037** [comment]
+1

**Comment by betaxab** [comment]
来晚了，作者已经消失了7个多月了。
