### ISSUE TITLE
始终报签名错误

### ISSUE THREAD

**Issue by huangkuan123** [lokielse/omnipay-wechatpay#13]
然后找不到发过去的到底是什么？最后找到了array2xml这个方法，这个方法返回的xml我给放到微信签名校验，是能通过的，但是外面一层setBody我不知道有没有成功，最终请求了微信那边的服务器，但不知道带过去的数据是什么，也不知道有没有把数据带过去。支付宝的成功了，微信的麻烦您再看下？

**Comment by lokielse** [comment]
`array2xml`方法的实现在中途修改过（原因见：https://github.com/lokielse/omnipay-wechatpay/issues/5#issuecomment-230216645 ），目前最新的实现见：https://github.com/lokielse/omnipay-wechatpay/blob/master/src/Helper.php

你可以和你本地的版本对照一下，如果不一样，请更新后再测试。

关于请求数据的调试，拿创建订单举例，你可以在 [CreateOrderRequest.php#L350](https://github.com/lokielse/omnipay-wechatpay/blob/master/src/Message/CreateOrderRequest.php#L350) 处调试, 你可以打印`Helper::array2xml($data)`的值来得到请求正文。当调用`$request->send()`时，请求就会发送到微信服务器

**Comment by huangkuan123** [comment]
您好，经测试，array2xml返回的xml字串没错。也请求到了微信的服务器，但是请求过去的数据是没有发送出去的。测试了一下午啦。怀疑是不是createorderrequest的sendData方法里面的setBody这里开始出了问题。但不知道有没有把这段xml发送到微信服务器，还是单单只是请求了没带数据过去。

**Comment by huangkuan123** [comment]
$request      = $this->httpClient->post($this->endpoint)->setBody(Helper::array2xml($data));
        dd($request);
        $response     = $request->send()->getBody();
        $responseData = Helper::xml2array($response);

```
    return $this->response = new CreateOrderResponse($this, $responseData);
```

在第二行中，打印出来的数据是没有Helper::array2xml($data)这个方法返回来的数据的，如果在$response     = $request->send()->getBody();这一行语句后打印$request也是找不到这段xml数据

**Comment by lokielse** [comment]
要这样打印

``` php
$request      = $this->httpClient->post($this->endpoint)->setBody(Helper::array2xml($data));
dd($request->getBody().'');
```

**Comment by lokielse** [comment]
你如果怀疑发送过去的数据与预期不一致，你可以把 `protected $endpoint = 'https://api.mch.weixin.qq.com/pay/unifiedorder'` 这个`endpoint`修改成自己服务器的地址，然后把接收到的数据记录一下，使用`file_get_contents('php://input')`可以获取到请求来的数据

**Comment by huangkuan123** [comment]
测试了，发送的数据没问题，用了官方的sdk做，也是报的签名错误，把xml放到校验里也是校验通过的，但是还是签名错误。郁闷了。谢谢您。

**Comment by lokielse** [comment]
看看是不是密钥格式有误 https://github.com/lokielse/omnipay-alipay/wiki/FAQ

**Comment by lokielse** [comment]
我把我的配置放上来，你看看

``` php
'wechat_app'             => [
            'driver'  => 'WechatPay_App',
            'options' => [
                'appId'     => 'wx90xxxxxxxxxxxxxxx',
                'mchId'     => '1321249562,
                'apiKey'    => 'e549a35xxxxxxxxxxx0a3c1923ce64a',
                'notifyUrl' => 'http://example.com/wechat-notify',
            ]
],
```

**Comment by lokielse** [comment]
看看这个 http://jingyan.baidu.com/article/59703552c3c9808fc1074072.html?st=2&os=0&bd_page_type=1&net_type=2

**Comment by huangkuan123** [comment]
真的是别人给我的key有问题。。。。谢谢，这项目搞完了，我会把这些遇到的坑和支付宝微信和这些插件的使用方式发到我个人博客上去您不会介意吧？，真的好用。

**Comment by lokielse** [comment]
没问题

**Comment by huangkuan123** [comment]
微信这边的回调过来了，路由地址是对的，能够直接访问，可以走到这条路由对应的方法里面去，也排除了csrf，但是微信服务器那边始终走不到这条路由对应的方法里面，但是看服务器日志这边是走了这条路由的，不知道您是不是用laravel做的，有没有遇到过这种情况啊？

**Comment by lokielse** [comment]
回调使用的应该是POST方法

**Comment by huangkuan123** [comment]
刚又测试了一下，支付宝的回调也坏了，应该是哪里文件坏了，我再找找
