### ISSUE TITLE
WechatPay_Js要用到的openid

### ISSUE THREAD

**Issue by huangkuan123** [lokielse/omnipay-wechatpay#14]
框架有封装获取这个参数的函数吗？是不是要自己去获取啊？

**Comment by lokielse** [comment]
获取方法见微信官方文档：https://mp.weixin.qq.com/wiki/4/9ac2e7b1f1d22e9e57260f6553822520.html#.E7.AC.AC.E5.9B.9B.E6.AD.A5.EF.BC.9A.E6.8B.89.E5.8F.96.E7.94.A8.E6.88.B7.E4.BF.A1.E6.81.AF.28.E9.9C.80scope.E4.B8.BA_snsapi_userinfo.29

也可以使用使用第三方SDK https://easywechat.org/zh-cn/docs/oauth.html
