### ISSUE TITLE
Please update dependency "omnipay/common" to version 3

### ISSUE THREAD

**Issue by videni** [lokielse/omnipay-wechatpay#19]
We use this package with our Symfony 3 project, the package "omnipay/common"  is dependent on "symfony/event-dispatcher"  2 version, which will conflict with  same package in Symfony3, Please update the dependency to  version 3, thanks a lot.

**Comment by lokielse** [comment]
`omnipay/common` 最新版本是`2.5.1`, 它是支持 `symfony3` 的（见 [L32](https://github.com/thephpleague/omnipay-common/blob/master/composer.json#L32)）

请执行` composer update lokielse/omnipay-wechatpay` 更新依赖

**Comment by videni** [comment]
But the   "guzzle/guzzle": "~3.9" requires "symfony/event-dispatcher": "~2.1", this is the problem

**Comment by lokielse** [comment]
的确，`"guzzle/guzzle": "~3.9"`依赖`"symfony/event-dispatcher": "~2.1"`
如果你的项目是确切的依赖`"symfony/event-dispatcher": "~3.0"`那就没办法了

一般是`symfony/http-kernel`需要依赖`symfony/event-dispatcher`, 但是依赖规则里面写的是`"symfony/event-dispatcher": "~2.8|~3.0"`, 所以这样也是可以安装的

你把` "lokielse/omnipay-wechatpay": "^1.0.19"`加入到依赖里面，再执行`composer update -vvv`, 如果不行就真的是不行的，只有找`omnipay/common`的作者来更新了
