### ISSUE TITLE
jsSDK提示签名错误

### ISSUE THREAD

**Issue by yeahcheung** [lokielse/omnipay-wechatpay#2]
jsSDK提示签名错误，经排查是加密类型没有加入到支付签名中导致。
vendor/lokielse/omnipay-wechatpay/src/Message/CreateOrderResponse.php中的getJSOrderData方法中

在数组$data中添加『'signType' => 'MD5',』
$data = array (
                'appId'     => $this->request->getAppId(),
                'package'   => 'prepay_id=' . $this->getPrepayId(),
                'nonceStr'  => md5(uniqid()),
                'timeStamp' => time(),
                'signType' => 'MD5',
            );

建议把
$data['sign'] = Helper::sign($data, $this->request->getApiKey());

改为
$data['paySign'] = Helper::sign($data, $this->request->getApiKey());

方便在js中直接使用

**Comment by lokielse** [comment]
谢谢提醒，已经修改好了
