### ISSUE TITLE
ios下报timestamp错误

### ISSUE THREAD

**Issue by yeahcheung** [lokielse/omnipay-wechatpay#3]
src\Message\CreateOrderResponse.php中42号中的time改为字符串

修改后代码：
            $time = time();
            $data = array (
                'appId'     => $this->request->getAppId(),
                'package'   => 'prepay_id=' . $this->getPrepayId(),
                'nonceStr'  => md5(uniqid()),
                'timeStamp' => "$time",
                'signType' => 'MD5',
            );

**Comment by lokielse** [comment]
建议你根据客户端的需要自行转换数据类型。

``` objective-c
PayReq *request = [[PayReq alloc] init];
request.partnerId = data[@"partnerid"];
request.prepayId = data[@"prepayid"];
request.package = data[@"package"];
request.nonceStr = data[@"noncestr"];
request.timeStamp = (UInt32) [data[@"timestamp"] integerValue];
request.sign = data[@"sign"];
[WXApi sendReq:request];
```
