### ISSUE TITLE
有获取openid的方法吗？

### ISSUE THREAD

**Issue by esolo0121** [lokielse/omnipay-wechatpay#31]
用的WechatPay_Js 公众号支付，而公众号支付，需要用户OPENID，找许久，源码里没有关于获取OPENID的代码，不知楼主是否有做相关功能？或者说是否有公众号支付的相关案例。以下是提示错误：
`The open_id parameter is required`

我的代码是：
`
        $gateway    = Omnipay::create('WechatPay_Js');
        $gateway->setAppId(config('pay.wechatpay.appid'));
        $gateway->setMchId(config('pay.wechatpay.mchid'));
        $gateway->setApiKey(config('pay.wechatpay.key'));
        $gateway->setNotifyUrl('http://example.com/notify');
        $gateway->setTradeType('JSAPI');

        $order = [
            'body'              => 'The test order',
            'out_trade_no'      => date('YmdHis').mt_rand(1000, 9999),
            'total_fee'         => 1, //=0.01
            'spbill_create_ip'  => 'ip_address',
            'fee_type'          => 'CNY'
        ];
`

**Comment by esolo0121** [comment]
期待你的回复

**Comment by lokielse** [comment]
@esolo0121 https://easywechat.org/zh-cn/docs/oauth.html

**Comment by phpstudyer** [comment]
@lokielse 额,貌似问题不在于怎么获取Open_id 而在于如何设置open_id .  setOpenId()并不存在

**Comment by lokielse** [comment]
@phpstudyer @esolo0121 
```php
$order = [
        'body'              => 'The test order',
        'out_trade_no'      => date('YmdHis').mt_rand(1000, 9999),
        'total_fee'         => 1, //=0.01
        'spbill_create_ip'  => 'ip_address',
        'fee_type'          => 'CNY',
        'open_id'           =>'xxxxxxx'
];
```

**Comment by lokielse** [comment]
@phpstudyer https://github.com/lokielse/omnipay-wechatpay/blob/90f7c72740597818d8a104cac1a6a75cfdb4f121/src/Message/CreateOrderRequest.php#L335 

有这个方法的...

**Comment by phpstudyer** [comment]
@lokielse 哈哈,我改了你的源码.你的这个方式也行.谢谢了

**Comment by esolo0121** [comment]
@lokielse 楼主给的链接 这个方法，只是设置openid，并不是获取。
@phpstudyer 能否上一份获取openid的方法？

`

public function setOpenId($openId)
--
  | {
  | $this->setParameter('open_id', $openId);
  | }

`

**Comment by phpstudyer** [comment]
@esolo0121 这个是微信这块的了.

public function getOpenId($appid, $secret, $jsCode, $grantType)
	{
		$url = "https://api.weixin.qq.com/sns/jscode2session?appid=$appid&secret=$secret&js_code=$jsCode&grant_type=$grantType";
		$res = json_decode(file_get_contents($url), true);
		if (isset($res['errcode'])) {
			throw new \Exception($res['errmsg']);
		}
		return $res['openid'];
}

这个是官方给的demo  可以直接用的

**Comment by esolo0121** [comment]
@phpstudyer 谢谢，我先试着用下

**Comment by esolo0121** [comment]
@phpstudyer @lokielse 我用我的方法也实现了，就是看着代码太乱，楼主是否能整合下获取openid的功能，这样用插件的意义就更大了

**Comment by lokielse** [comment]
不整合，见我第一个回复。
