### ISSUE TITLE
有可能是个严重的问题

### ISSUE THREAD

**Issue by waveiron** [lokielse/omnipay-wechatpay#32]
<img width="523" alt="1" src="https://user-images.githubusercontent.com/4930447/28083443-efa89b70-66a7-11e7-9f4f-90c8ee8c5e63.png">
在订单只是创建并未支付的情况下调用`$res->isPaid()`会返回`true`。
是我的用法不对？

**Comment by lokielse** [comment]
@waveiron 你这个数据是什么接口下得到的？是支付异步通知的数据验证吗？

根据官方文档，没有`trade_state`这个参数呢

https://pay.weixin.qq.com/wiki/doc/api/app/app.php?chapter=9_7&index=3  

文档中明确提出 `交易是否成功需要查看result_code来判断`

**Comment by lokielse** [comment]
https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_2

查询订单接口有这个返回参数`trade_state`，但是没有`QueryOrderResponse`这个类并没有`isPaid`这个方法
