### ISSUE TITLE
希望添加一个 .php_cs.dist 文件以更好的方便修正代码格式

### ISSUE THREAD

**Issue by dacheng-gao** [lokielse/omnipay-wechatpay#48]
@lokielse 你好。

你能不能添加一个适合本项目的 .php_cs.dist 文件？

参考： [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) 项目。

**Comment by lokielse** [comment]
@DarrenGDC 高先生你好，本项目遵循PSR2代码风格。

这里有代码格式检测及修正的方案 [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer)

本项目中有一个`.travis.yml`文件，里面的`vendor/bin/phpcs --standard=PSR2 src`是检测代码风格的命令。

如果检测出来有问题，可以通过 [phpcbf](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Fixing-Errors-Automatically) 工具来修复。 

如果你用`php-cs-fixer`，也可以用一行命令就行修正。
```
php-cs-fixer fix . --rules=@PSR2
```

**Comment by dacheng-gao** [comment]
hello @lokielse  PSR2 规则里面的每个方法的后面没说是几个空行，以及，类的开始的第一行没有留空行，你确定是用的PSR2规则吗？还有那个类的注释里的phpdoc里的@package如果用PSR2进行修复的话，会被整没了的。

不过，我稍后会再详细check一下php-cs-fixer的用法，以及你提到的phpcbf命令。

**Comment by dacheng-gao** [comment]
我会使用PSR2。本issue将关闭。
