### ISSUE TITLE
array2xml方法是不是有问题

### ISSUE THREAD

**Issue by icyfire** [lokielse/omnipay-wechatpay#5]
调用接口时一直返回签名错误，但是改用微信demo里的toXml方法就正常了。

**Comment by lokielse** [comment]
1. 请提供一下传入array2xml的参数
2. 以及PHP版本号

**Comment by icyfire** [comment]
今天居然复现不了这个问题，现在一切正常。

不好意思。

**Comment by lokielse** [comment]
恩，应该还是有问题的，重现了的时候把数据贴上来:D

**Comment by lokielse** [comment]
@icyfire 这个bug现已修复。
当请求参数存在相同的值的时候就会出现bug, 比如`body`和`total_fee`都传`123`。

**Comment by icyfire** [comment]
Good job!应该是array_flip引起的问题。
