### ISSUE TITLE
WechatPay_Native 微信支付问题

### ISSUE THREAD

**Issue by pangxioujiang** [lokielse/omnipay-wechatpay#59]
$gateway    = Omnipay::create('WechatPay_Native');
        $gateway->setAppId('wx0b2cb4687763f2c5');
        $gateway->setMchId('1303570701');
        $gateway->setApiKey('qK2Szcejbv19r9hI6VbaqodqpH3x5mXd');
$order = [
            'body'              => 'The test order',
            'out_trade_no'      => date('YmdHis').mt_rand(1000, 9999),
            'total_fee'         => 0.01, //=0.01
            'spbill_create_ip'  => 'ip_address',
            'fee_type'          => 'CNY'
        ];

        $request  = $gateway->purchase($order);
        $response = $request->send();

        $response->isSuccessful();
        $response->getData(); //For debug
        $response->getAppOrderData(); //For WechatPay_App
        $response->getJsOrderData(); //For WechatPay_Js
        $response->getCodeUrl(); //For Native Trade Type

Omnipay \ Common \ Exception \ InvalidRequestException
The notify_url parameter is required

**Comment by dacheng-gao** [comment]
@pangxioujiang 

> The notify_url parameter is required

请你设置一下 `notify_url` 字段呗

**Comment by pangxioujiang** [comment]
//            $gateway->setNotifyUrl(config("laravel-omnipay.gateways.alipay.options.returnUrl")); //回调地址

            $gateway->setNotifyUrl("https://paysdk.weixin.qq.com/example/notify.php");   微信官网调试数据

设置后，页面上是一片空白，什么都没有呢，没有提示错误！

**Comment by solody** [comment]
qq.com是你家的域名？
