### ISSUE TITLE
能不能给个企业付款的文档或demo？

### ISSUE THREAD

**Issue by caveychen** [lokielse/omnipay-wechatpay#60]
@gdc5p 
正好需要用到企业付款的功能，研究了半天没看明白，能不能给个文档或者demo，详细说明下方法怎么调用的？参数是怎么传递的？

**Comment by lokielse** [comment]
转账用`transfer`方法

```php
$response = $gateway->transfer([
    'open_id'=>'xxxxxxxx',
    'amount'=> 0.01,
    //...more parameters
])->send();
```

详见转账请求类

https://github.com/lokielse/omnipay-wechatpay/blob/bd6f40a7f3e47bcd3088e371589885746c78db1c/src/Message/PromotionTransferRequest.php#L17

**Comment by dacheng-gao** [comment]
微信企业付款到零钱的文档，参见： [这里](https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=14_2) 。
