### ISSUE TITLE
请更新一下 composer包`lokielse/omnipay-wechatpay`

### ISSUE THREAD

**Issue by kanghuli** [lokielse/omnipay-wechatpay#64]
pull request 不能把  `tag` 合并到原代码仓库？
请作者帮忙做个新版: v1.0.23 , 并更新一下 composer包`lokielse/omnipay-wechatpay`
感谢！

**Comment by dacheng-gao** [comment]
@kanghuli 

release需要原仓库作者重新操作。

ping @lokielse

**Comment by kanghuli** [comment]
@lokielse 
项目中用到您的composer包， 请您帮忙操作哈，ps:尊重原创

**Comment by dacheng-gao** [comment]
@kanghuli 

在作者打tag之前，您还有一个可选的方法，将版本号写为dev-master，直接拉取git上的master分支。

**Comment by kanghuli** [comment]
@gaodacheng5percent  
哈哈，昨天就是这么做的。

**Comment by dacheng-gao** [comment]
@kanghuli   Nice bro!

让我们等作者吧， 大家都是有工作的，比较忙呢！所以呢，so 让我们多点耐心。

**Comment by lokielse** [comment]
@kanghuli `v1.0.23` released
