### ISSUE TITLE
微信刷卡支付为何不做的跟支付宝条码支付的形式一致?

### ISSUE THREAD

**Issue by miaotaizi** [lokielse/omnipay-wechatpay#67]
强迫症的我有些难受(请原谅), 有什么原因吗?

**Comment by lokielse** [comment]
好问题！原(jie)因(kou)如下：

首先，这个问题和组件的目标有关。`omnipay` 致力于整合全球主要的支付渠道，将他们一同样的方式完成构造支付请求、验证支付以及相关业务。并没有强制规范参数或者类似网关的使用相同的形式，当然，可能存在一些惯例和默契。汝之**idea**与之不冲突，在此之上。

其次，本人在完成支付宝，微信，银联等支付渠道的实现主要参考了各自的官方文档，按照`omnipay-style`来进行封装。并完成于不同的时期，参数的同意或者调用的一致性方面没有考虑过多。并且个人主要使用了网页支付和移动支付，类似刷卡支付、扫码支付并未在生产环境使用过。。。，所以不会碰到此方面的不一致。而且我只是解决了有无的问题，至于好不好用，既然你提出了这个问题，我想肯定是不好用，有很多改进的地方。

最后，正如上述原因，我可能至此还不明白你遇到的具体的不一致是指的什么，当看到你的问题时，我甚至自问『微信也有条码支付吗？』，于是乎赶紧去瞅瞅代码。。。你可以把问题明确一点，方便你我讨论，也方便后人看到，或者直接来个完美的PR。

言归正传，主观原因就是我没有心去发现这些问题，客观原因是我没有太多工夫来搞这个。以至于你提出来后我可能要等很久才能搞定它，或者根本就不会搞。但是，这一切都是我的问题，你的心很细，想法非常好！不是因为你有强迫症，这种想法就很高端！

还是那句话，要实现更完美的目标需要一个过程，欢迎你以及各位 PR。或者造个新轮子，名字我都想好了，就叫`ElsePay`吧... 我其实早已无法忍受`omnipay`这种写个B代码还要不停的写`php-doc`，搞得老子都不想写PHP了

**Comment by miaotaizi** [comment]
不过你的组建依然很好用，至于调用统一的问题，我们可以慢慢来。（我都不知道如何提pr）
