### ISSUE TITLE
getJsOrderData返回数据到小程序后出错了。

### ISSUE THREAD

**Issue by unizhu** [lokielse/omnipay-wechatpay#68]
小程序调用getJsOrderData返回的数据 : 

例如：
wx.requestPayment({
      'timeStamp': '1523333222',
      'nonceStr': 'f451b1286827c667c666668df727444',
      'package': 'prepay_id=wx12226666666370dd3f971eaa1134666743',
      'signType': 'MD5',
      'paySign': '9CA1CDF5B24B882C6DFE93F782EF7BFD',
})

微信发起了支付，但是显示无法验证签名的错误： 
{err_code: 2, err_desc: "Unable to verify signature", errMsg: "requestPayment:fail"}

不知道小程序的支付签名方式是不是又有什么坑了？
谢谢。

**Comment by ghost** [comment]
你好，怎么解决的？
