### ISSUE TITLE
商户号该产品权限未开通

### ISSUE THREAD

**Issue by zhu6621** [lokielse/omnipay-wechatpay#71]
{
	"return_code": "FAIL",
	"return_msg": "商户号该产品权限未开通，请前往商户平台>产品中心检查后重试"
}

APP微信支付时，返回这个错误。这是什么问题，开放平台已经绑定该公众号了。后台填的是公众号app_id，商户号mch_id，支付密钥api_key。我在网页中测试微信扫码支付时正常，可以支付。

**Comment by lokielse** [comment]
请问在调用 `Omnipay::create('???')` 时，传的是哪个网关？

**Comment by zhu6621** [comment]
$gateWay = Omnipay::create('WechatPay_App');   WechatPay_App

**Comment by lokielse** [comment]
应该是使用了错误的网关，请参考网关列表，选择此场景需要的网关。

https://github.com/lokielse/omnipay-wechatpay#basic-usage

**Comment by zhu6621** [comment]
APP 支付时就是这个  WechatPay_App   这个网关啊，还有其他网关？

**Comment by lokielse** [comment]
如果是APP支付，填写公众号的app_id是不是不太合适？
