### ISSUE TITLE
报告一个异常，具体产生原因未知

### ISSUE THREAD

**Issue by wslsq** [lokielse/omnipay-wechatpay#72]
[laravel.log](https://github.com/lokielse/omnipay-wechatpay/files/2098295/laravel.log)

```
ksort() expects parameter 1 to be array, boolean given at /src/Helper.php:33
```

**Comment by lokielse** [comment]
Thank you, fixed in [`v3.0.5`](https://github.com/lokielse/omnipay-wechatpay/commit/7c6e671ac22d8c0b0aa7dd3cdfc7684a73d596b7)
