### ISSUE TITLE
xml2array 有问题

### ISSUE THREAD

**Issue by firefly0621** [lokielse/omnipay-wechatpay#74]
helper类中xml2array函数始终返回[];

**Comment by firefly0621** [comment]
作者帮忙给解决下呗,啥提示没有只返回 null,

**Comment by firefly0621** [comment]
我微信商户没有app支付权限,但是有扫码支付权限,为什么还是返回空,

**Comment by lokielse** [comment]
自己调试一下吧...

**Comment by firefly0621** [comment]
哇,您终于回复了,之前接口扫码支付还是正常的,现在告诉我没有开通权限,我们这只是没有app支付权限,扫码支付还是可以用的,

**Comment by firefly0621** [comment]
代码没动,就升级了下,然后就不能用了,

**Comment by lokielse** [comment]
建议你自行debug一下，比如在sendData中把即将发送到微信服务端的数据记录一下，看看和老版有何不同？

**Comment by lokielse** [comment]
<img width="903" alt="default" src="https://user-images.githubusercontent.com/1573211/42306406-677518f8-8061-11e8-935f-0409adbe5954.png">

https://github.com/lokielse/omnipay-wechatpay/releases
v3 的代码更新你可以自行检阅一下。

**Comment by firefly0621** [comment]
我能说一模一样吗,

**Comment by lokielse** [comment]
我能说自行调试知道找到具体问题再来提issue吗，

**Comment by lokielse** [comment]
xml2array的入参xml是啥？

**Comment by firefly0621** [comment]
<xml><return_code><![CDATA[SUCCESS]]></return_code>
<return_msg><![CDATA[OK]]></return_msg>
<appid><![CDATA[wx57b9bd4dd4b01ef5]]></appid>
<mch_id><![CDATA[1499803642]]></mch_id>
<nonce_str><![CDATA[k5ntjxBlcq0KnkJQ]]></nonce_str>
<sign><![CDATA[8C03594BEB37A08BE70422F9FCC05168]]></sign>
<result_code><![CDATA[SUCCESS]]></result_code>
<prepay_id><![CDATA[wx05153421914401e72549e4843149659371]]></prepay_id>
<trade_type><![CDATA[NATIVE]]></trade_type>
<code_url><![CDATA[weixin://wxpay/bizpayurl?pr=QXuSXeo]]></code_url>
</xml>

**Comment by firefly0621** [comment]
`<xml><return_code><![CDATA[SUCCESS]]></return_code>
<return_msg><![CDATA[OK]]></return_msg>
<appid><![CDATA[wx57b9bd4dd4b01ef5]]></appid>
<mch_id><![CDATA[1499803642]]></mch_id>
<nonce_str><![CDATA[k5ntjxBlcq0KnkJQ]]></nonce_str>
<sign><![CDATA[8C03594BEB37A08BE70422F9FCC05168]]></sign>
<result_code><![CDATA[SUCCESS]]></result_code>
<prepay_id><![CDATA[wx05153421914401e72549e4843149659371]]></prepay_id>
<trade_type><![CDATA[NATIVE]]></trade_type>
<code_url><![CDATA[weixin://wxpay/bizpayurl?pr=QXuSXeo]]></code_url>
</xml>`

**Comment by firefly0621** [comment]
public static function xml2array($xml)
    {
        $data = json_decode(json_encode(simplexml_load_string($xml, 'SimpleXMLElement', LIBXML_NOCDATA)), true) || [];

        if (! is_array($data)) {
            $data = [];
        }

        return $data;
    }

**Comment by firefly0621** [comment]
```php
public static function xml2array($xml)
    {
        $data = json_decode(json_encode(simplexml_load_string($xml, 'SimpleXMLElement', LIBXML_NOCDATA)), true) || [];

        if (! is_array($data)) {
            $data = [];
        }

        return $data;
    }
```
这$data要么为真要么为假吧

**Comment by lokielse** [comment]
好的，感谢提供信息，稍候更新。

**Comment by lokielse** [comment]
已在[`v3.0.7`](https://github.com/lokielse/omnipay-wechatpay/releases/tag/v3.0.7)中更新。
