### ISSUE TITLE
微信支付官方SDK存在的严重漏洞

### ISSUE THREAD

**Issue by hookewin** [lokielse/omnipay-wechatpay#75]
https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=23_5
请问这个包会有这个问题吗？

**Comment by lokielse** [comment]
大家应该都收到通知了。请按照官方指示在程序合适的位置加上相关代码以防止攻击。大部分开发者只需要在支付回调接口中加入以下代码即可。

libxml_disable_entity_loader(true);

**Comment by hookewin** [comment]
好的，这个包应该也会做相应修改吧？

**Comment by lokielse** [comment]
应该会的吧

**Comment by gaodevops** [comment]
xml2array 方法 不修复下？？

**Comment by lokielse** [comment]
@gaodevops xml2array 已修复了
