### ISSUE TITLE
退款申请请求错误

### ISSUE THREAD

**Issue by zudar** [lokielse/omnipay-wechatpay#8]
lokielse/omnipay-wechatpay 1.0.15

Omnipay\WechatPay\Message\RefundOrderRequest.php的sendData方法中
调用$this->httpClient->post时，$options未成功设置，可使用

$this->httpClient->setConfig([Client::CURL_OPTIONS=>$options]);
        $responseData = Helper::xml2array(
            $this->httpClient->post($this->endpoint, null, $data)->setBody(Helper::array2xml($data))->send(
            )->getBody()
        );

**Comment by lokielse** [comment]
谢谢指正，已经修改。

我查了下文档, [custom-cURL-option](http://guzzle3.readthedocs.io/http-client/request.html#custom-curl-options), 应该这样写比较好

``` php
$request->getCurlOptions()->merge($options);
```
